import { useState } from 'react'
import { Download, FileText, Printer } from 'lucide-react'
import { useSelector } from 'react-redux'
import { selectCurrentUser } from '../../store/slices/authSlice'
import toast from 'react-hot-toast'
import api from '../../utils/api'

export default function Marksheet() {
  const user      = useSelector(selectCurrentUser)
  const [loading, setLoading] = useState(false)

  const downloadPDF = async () => {
    setLoading(true)
    try {
      const resp = await api.get('/reports/marksheet', {
        params:       { academicYear:'2024-2025', semesterId:4 },
        responseType: 'blob',
      })
      const url = URL.createObjectURL(resp.data)
      const a   = document.createElement('a')
      a.href      = url
      a.download  = `marksheet_${user?.email?.split('@')[0]}_2024-2025.pdf`
      a.click()
      URL.revokeObjectURL(url)
      toast.success('Marksheet downloaded!')
    } catch { toast.error('Failed to generate marksheet') } finally { setLoading(false) }
  }

  return (
    <div className="space-y-6 animate-fade-in">
      <div>
        <h1 className="page-title">My Marksheet</h1>
        <p className="page-subtitle">Download your official Internal Assessment Marksheet</p>
      </div>

      <div className="max-w-2xl mx-auto space-y-6">
        {/* Preview card */}
        <div className="glass-card p-8 text-center space-y-6">
          <div className="w-16 h-16 rounded-2xl bg-primary-500/20 flex items-center justify-center mx-auto">
            <FileText className="w-8 h-8 text-primary-400"/>
          </div>

          <div>
            <h2 className="text-xl font-bold text-white">Internal Assessment Marksheet</h2>
            <p className="text-slate-400 text-sm mt-1">Academic Year 2024-2025 · Semester 4</p>
          </div>

          <div className="grid grid-cols-2 gap-4 text-sm text-left">
            <div className="glass rounded-xl p-3">
              <p className="text-slate-500 text-xs">Student Name</p>
              <p className="text-white font-medium mt-0.5">{user?.firstName} {user?.lastName}</p>
            </div>
            <div className="glass rounded-xl p-3">
              <p className="text-slate-500 text-xs">Email</p>
              <p className="text-white font-medium mt-0.5 truncate">{user?.email}</p>
            </div>
            <div className="glass rounded-xl p-3">
              <p className="text-slate-500 text-xs">Department</p>
              <p className="text-white font-medium mt-0.5">Computer Science</p>
            </div>
            <div className="glass rounded-xl p-3">
              <p className="text-slate-500 text-xs">Semester</p>
              <p className="text-white font-medium mt-0.5">4th Semester</p>
            </div>
          </div>

          <div className="flex flex-col sm:flex-row gap-3 justify-center">
            <button
              onClick={downloadPDF}
              disabled={loading}
              className="btn-primary flex items-center justify-center gap-2 text-sm px-8 py-3"
            >
              <Download className="w-4 h-4"/>
              {loading ? 'Generating PDF…' : 'Download PDF Marksheet'}
            </button>
            <button
              onClick={() => window.print()}
              className="btn-secondary flex items-center justify-center gap-2 text-sm px-6 py-3"
            >
              <Printer className="w-4 h-4"/> Print
            </button>
          </div>
        </div>

        {/* Info note */}
        <div className="glass border border-blue-500/20 rounded-xl p-4 text-blue-300 text-sm space-y-1">
          <p className="font-medium">📋 About this Marksheet</p>
          <ul className="text-xs text-blue-300/70 space-y-1 mt-2 list-disc list-inside">
            <li>Includes CIE 1, CIE 2, CIE 3, Assignment, Lab Internal and Attendance marks</li>
            <li>Only marks with <strong>Approved</strong> or <strong>Locked</strong> status are included</li>
            <li>This is an official document generated by the Student Portal</li>
            <li>Contact your HOD for discrepancies</li>
          </ul>
        </div>
      </div>
    </div>
  )
}
